### ISSUE TITLE
ModuleNotFoundError dr_geodesic_gaussian

### ISSUE THREAD

**Issue by KirillHiddleston** [VCL3D/PanoDR#2]
from .dr_geodesic_gaussian import *
ModuleNotFoundError: No module named 'vcl3datlantis.dataloaders.dr_geodesic_gaussian'
can you add this module ?

**Comment by VasilisGks** [comment]
Sorry for the inconvenience, this line has been removed and you can run the inference script.

**Comment by KirillHiddleston** [comment]
after remove we have same results 

"initialize network with normal
Freezing Layout segmentation network's weights"

that's all

**Comment by VasilisGks** [comment]
You should be able to see a created folder "./input/output" with the DR results. Can you reproduce this?

**Comment by KirillHiddleston** [comment]
Yes, paths correctly 
for example

    parser.add_argument('--train_path', type=str, default='')
    parser.add_argument('--test_path', type=str, default='')
    parser.add_argument('--results_path', type=str, default='my_path/output')
    parser.add_argument('--eval_path', type=str, default='my_path/PanoDR/input')
    parser.add_argument('--eval_chkpnt_folder', type=str, default= 'my_path/model/PanoDR_net_G.pth')
    parser.add_argument('--gt_results_path', type=str, default='my_path/output')
    parser.add_argument('--pred_results_path', type=str, default='my_path/output')
    parser.add_argument('--segmentation_model_chkpnt', type = str, default = 'my_path/models/Unet_layout.model', help = 'Save checkpoints here')

**Comment by VasilisGks** [comment]
According to your input, the generated images should be in the folder: "my_path/PanoDR/input/output/"

**Comment by KirillHiddleston** [comment]
my_path/PanoDR/input/output/ - there is an image in this folder 'img_1.png' or 'mask_1.png' or both files ? I tested both options
and results"
"initialize network with normal
Freezing Layout segmentation network's weights"

you have the following  README test.py --eval_path input/

Sorry for so many questions

**Comment by VasilisGks** [comment]
Regarding the terminal output, for inference this is the expected behavior. As far as concerns the input/out folders,  "my_path/PanoDR/input/" should contain couples of "img_X, mask_X". For instance, in the provided samples, for each img_X, its corresponding mask_X should be present. Subsequently, the results are saved in  "my_path/PanoDR/input/output".

**Comment by KirillHiddleston** [comment]
empty results output folder in Mac OS and Ubuntu

**Comment by VasilisGks** [comment]
Please for --eval_path try: 'my_path/PanoDR/input/',  not 'my_path/PanoDR/input'

**Comment by KirillHiddleston** [comment]
Thank you so much I did it all. But 
Requirements is missing some libraries and versions, I'll add them all and commit
