### ISSUE TITLE
pretrain Unet model

### ISSUE THREAD

**Issue by YuChengHsieh** [VCL3D/PanoDR#3]
Hello, thank you for great works!!!  would you release pretrain Unet model for structure semantics?

**Comment by VasilisGks** [comment]
Hi @shieh322, you can find the pre-trained UNet model here:  https://drive.google.com/drive/u/1/folders/1TD0wJe4EncunD-ZiQ9RTQVXbIv-1Snz6

**Comment by YuChengHsieh** [comment]
Thank you very much, I really appreciate it.
